### ISSUE TITLE
Font loading error in rom/emulator r38

### ISSUE THREAD

**Issue by jestin** [theelkmechanic/ziggurat#1]
Trying to load the application in r38, I get an error about fonts:

![error](https://user-images.githubusercontent.com/669174/91509671-c9b0dc80-e88f-11ea-9d9e-37a5756ce30b.gif)

I haven't had a chance to look through the source yet, so I'm not in a great position to fix this myself.  Hopefully, I'll get a chance, and maybe even be able to submit a PR.

**Comment by theelkmechanic** [comment]
I knew stuff would break with r38, so now that it's out I'll have to take a look.

**Comment by jestin** [comment]
If it helps, there's a thread on the Commander X16's forum that is discussing unexpected breaking changes between r37 and r38:

https://www.commanderx16.com/forum/index.php?/topic/407-emulator-r38-released/

Several people talking about loading sd card contents into banks, which sounds suspicious.

**Comment by theelkmechanic** [comment]
Finally got this figured out by stealing the directory loading code from the r38 kernal to load directory/files into high ram and by just using the kernal LOAD call to load the font into VRAM. Version 0.0.7 should work now.

**Comment by jestin** [comment]
Thanks!  I'm able to open games now!  I'll probably run through some and see if everything runs smoothly.
